[default]
protoPath = ["src/main/proto"]
protoFile = ["helloWorld.proto"]
package = "com.lc.grpc.service"
service = "HelloWorld"

[health]
protoPath = ["src/main/health-check"]
protoFile = ["health.proto"]
package = "grpc.health.v1"
service = "Health"

